version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_DATA_DIR: ./rtm-data/zookeeper/data:/data
      ZOOKEEPER_LOG_DIR: ./rtm-data/zookeeper/datalog:/datalog
    volumes:
      - ./rtm-data/zookeeper/data:/data
      - ./rtm-data/zookeeper/datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_DATA_DIR: ./rtm-data/kafka/data:/data
      KAFKA_LOG_DIR: ./rtm-data/kafka/datalog:/datalog
      KAFKA_CREATE_TOPICS: random-pokemon:1:1
    volumes:
      - ./rtm-data/kafka/data:/data
      - ./rtm-data/kafka/datalog:/datalog

  producer:
    build:
      context: ./backend/realtime-producer
      dockerfile: Dockerfile
    depends_on:
      - kafka

  consumer:
    build:
      context: ./backend/realtime-consumer
      dockerfile: Dockerfile
    depends_on:
     - producer